config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|pt/ do
    resources :rooms, :users
    resource :confirmation, only: [:show]
    resource :user_sessions, only: [:create, :new, :destroy]
  end

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  #Relations
  belongs_to :user

  def complete_name
    "#{title}, #{location}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  #Relations
  has_many :rooms

  #Scopes
  scope :confirmed, -> { where.not(confirmed_at: nil)}
  
  #Validations
  validates_presence_of :email, :full_name, :location
  #validates_confirmation_of :password
  validates_length_of :bio, minimum: 30, allow_blank: false
  validates_format_of :email, with: EMAIL_REGEXP
  validates_uniqueness_of :email
  # validates_format_of :email, with: EMAIL_REGEXP
  
  #validate :email_format

  has_secure_password

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    confirmed.find_by(email: email).try(:authenticate, password)
  end

  private

  def email_format
    errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
=begin
  Error messages
    • accepted: must be accepted (precisa ser aceito)
    • blank: can’t be blank (não pode ficar em branco)
    • confirmation: doesn’t match confirmation (não é igual a confirmação)
    • empty: can’t be empty (não pode ficar vazio)
    • equal_to: must be equal to %{count} (precisa ser igual a count)
    • exclusion: is reserved (é reservado)
    • greater_than: must be greater than %{count} (precisa ser maior que
count)
    • greater_than_or_equal_to: must be greater than or equal to %{count}
(maior ou igual que count)
    • inclusion: is not included in the list (não está na lista)
    • invalid: is invalid (é invalido)
    • less_than: must be less than %{count} (precisa ser menor que count)
    • less_than_or_equal_to: must be less than or equal to %{count} (menor
ou igual que count)
    • not_a_number: is not a number (não é um número)
=end
  end

  
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model

  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(session={}, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate!
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?

  before_action do
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login')
    end
  end

  def require_no_authentication
    if user_signed_in?
      redirect_to root_path, notice: t('flash.notice.already_logged_in')
    end
  end

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

  def show
    user = User.find_by(confirmation_token: params[:token])

    if user.present?
      user.confirm!
      redirect_to user, notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @rooms = Room.take(3)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]
  before_action :set_users_room, only: [:edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t('flash.notice.room_created') }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: t('flash.notice.room_updated') }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: t('flash.notice.room_destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    def set_users_room
      @room = current_user.rooms.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: [:destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(session, user_session_params)

    if @user_session.authenticate!
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      Signup.confirm_email(@user).deliver

      redirect_to @user, notice: 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user,
                  notice: 'Cadastro atualizado com sucesso!'
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
          :div,
          model.errors[attribute].first,
          class: 'error_message'
      )
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>
<ul>
  <% @rooms.each do |room| %>
      <li><%= link_to room.complete_name, room %></li>
  <% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %> </li>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li>
      <%= link_to t('layout.my_profile'),
          user_path(current_user) %>
    </li>
    <li>
      <%= link_to t('layout.signout'), user_sessions_path,
              method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %> </li>
    <li><%= link_to t('layout.signup'), new_user_path %> </li>
    <li>
      <%= link_to t('layout.signin'), new_user_sessions_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div id="header-wrap">
    <h1><%= link_to "colcho.net", root_path %> </h1>
    <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
    <% else %>
        <%= render 'layouts/visitor_navbar' %>
    <% end %>
  </div>
</header>

<div id="content">
  <% if notice.present? %>
      <p id="notice"><%= notice %> </p>
  <% end %>
  <% if alert.present? %>
      <p id="alert"><%= alert %> </p>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <%= t 'general.form_error' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= error_tag @room, :title %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= error_tag @room, :location %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= error_tag @room, :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<article class="rooms">
  <h2><%= link_to room.title, room %></h2>
      <span class="created">
        <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
      </span>

  <p>
        <span class="location">
          <%= link_to room.location, "https://maps.google.com/?q=#{room.location}", target: :blank %>
        </span>
  </p>

  <p>
    <%= room.description %>
  </p>
  <% if belongs_to_user(room) %>
      <ul>
        <li><%= link_to t('.edit'), edit_room_path(room) %></li>
        <li><%= link_to t('.destroy'), room_path(room), method: :delete, data: {confirm: t('dialogs.destroy')} %></li>
      </ul>
  <% end %>
</article>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1><%= t '.title' %></h1>

<%= render @rooms %>

app/views/rooms/new.html.erb
<h1><%= t '.title' %> </h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %> </h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html',
        link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
  <%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>
<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>
<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %> </h1>
<% if @user_session.errors.has_key? :base %>
    <div id="error_explanation">
      <%= @user_session.errors[:base].join(', ') %>
    </div>
<% end %>
<%= form_for @user_session do |f| %>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user_session, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user_session, :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>
<p><%= link_to t('.sign_up'), new_user_path %> </p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <%= t 'general.form_error' %>
    </div>
<% end %>

<%= form_for @user do |f| %>
    <p>
      <%= f.label :full_name %>
      <%= f.text_field :full_name %>
      <%= error_tag @user, :full_name %>
    </p>
    <p>
      <%= f.label :location %>
      <%= f.text_field :location %>
      <%= error_tag @user, :location %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= error_tag @user, :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= error_tag @user, :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= error_tag @user, :password_confirmation %>
    </p>
    <p>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
      <%= error_tag @user, :bio %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %> </h1>

<%= render "form" %>

<%= link_to "Voltar ao perfil", @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %> </h1>

<%= render "form" %>

<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h1><%= t '.title', user_name: @user.full_name %> </h1>

<ul>
  <li><%= t '.location', location: @user.location %> </li>
  <li><%= t '.bio', bio: @user.bio %> </li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>